require './gulp_tasks/path.coffee'
require './gulp_tasks/jade.coffee'
require './gulp_tasks/connect.coffee'
require './gulp_tasks/watch.coffee'
require './gulp_tasks/email.coffee'
require './gulp_tasks/default.coffee'